### ISSUE TITLE
Swap markdown images with own CDN

### ISSUE THREAD

**Issue by BelieveInBunny** [torrust/torrust-index-frontend#5]
closed by #67

**Comment by josecelano** [comment]
Now we have an [image proxy with a cache in the backend](https://github.com/torrust/torrust-index-backend/tree/develop/src/web/api/v1/contexts/proxy).

Is that what you meant @BelieveInBunny?

**Comment by josecelano** [comment]
@da2ce7 did you add the "duplicate" label because of [this issue](https://github.com/torrust/torrust-index-frontend/issues/67)?

**Comment by josecelano** [comment]
I think this is an concrete case of https://github.com/torrust/torrust-index-frontend/issues/67
